### ISSUE TITLE
exception during run

### ISSUE THREAD

**Issue by weihangChen** [biosignalsplux/android-sample#2]
1. every time when it starts to receive signal it always get into this exceptoin

W/System.err: info.plux.api.PLUXException: Device not in idle mode
        at info.plux.api.bioplux.bth.BTHCommunication.start(BTHCommunication.java:204)
W/System.err:     at info.plux.android.sample.DeviceActivity$2.onReceive(DeviceActivity.java:368)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1185)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

![image](https://user-images.githubusercontent.com/2369864/94162965-94e07700-fe87-11ea-9fa4-0a878588309f.png)

2. when the sequence comes to 32000, it always stops the update, is there something special with sequence 32000?

**Comment by weihangChen** [comment]
my device is biosignalsplux8ch
pid: 513
fw version: 775
hw version: 4352

```
D/DeviceActivity: Identifier: 00:07:80:F9:DD:CB; Sequence: 31000; AnalogData: [32824, 32824, 32768, 32816]; DigitalInput: 0; Comments: null
D/DeviceActivity: Identifier: 00:07:80:F9:DD:CB; Sequence: 32000; AnalogData: [32812, 32808, 32812, 32808]; DigitalInput: 0; Comments: null
```

after 32 seconds, it is not able to receive any `info.plux.android.sample.DeviceActivity.FRAME`, but only `info.plux.android.sample.DeviceActivity.ELAPSED_TIME_EVENT`

**Comment by weihangChen** [comment]
here is another problem, every time stop and start the signal, the analogdata array is increased by one
![data_increse_by_one_error](https://user-images.githubusercontent.com/2369864/94265147-53f46b00-ff38-11ea-87f2-ae8b0d960248.jpg)

**Comment by v-gramos** [comment]
Hi Marc,

The exception that you are obtaining is related with the flag `settingParameter` that should be set to false and is wrongly set to true. Regarding the problem that you are facing with the analog data array, we apologize for the inconvenience and thank you for alerting us. It was a bug. We have fixed the problem and I have just uploaded the corrected version.

There should be nothing special with the 32000 and the device should not stop the acquisition if there was no order to stop. Can you please check if after that time the device is still in acquisition. To do so you just need to check if the LED is blinking twice.

Best regards,
Vanessa Ramos

**Comment by weihangChen** [comment]
Thanks @v-gramos , now the stopping at 32000 went away, maybe it is due to the exception. I can verify that everything is working fine now, have a nice weekend!!

**Comment by v-gramos** [comment]
I'm glad to know that everything is working fine. Have a nice weekend too!
