### ISSUE TITLE
question about receive frequency

### ISSUE THREAD

**Issue by weihangChen** [biosignalsplux/android-sample#3]
we have the requirement to obtain signals every 100ms, while in the sample project, the time interval is 1s. So i tried to modify some variables and see if there is difference.

```
private int samplingRate = 200;  //original value 1000
private long TIME_1_SECOND = 500; //original value 1000
```

the elapse time is shortened from 1s to 500ms, but I am still getting signals every 1s despite the changes in the handler

```

handler = new Handler(getMainLooper()) {
            @RequiresApi(api = Build.VERSION_CODES.O)
            @Override
            public void handleMessage(Message msg) {
                final Bundle bundle = msg.getData();

                if (bundle.containsKey(FRAME)) {
                    Tick++;
                    final Parcelable frame = bundle.getParcelable(FRAME);

                    if (frame.getClass().equals(BiopluxFrame.class)) { //biosignalsplux
                        String frameStr = frame.toString();

                        int[] datas=  ((BiopluxFrame) frame).getAnalogData();
                        if (datas.length>0) {
                            double convertedValue1 = ConvertRawData(datas[0]);
                            series1.appendData(new DataPoint(Tick, convertedValue1),
                                    false ,
                                    20,
                                    false);

                            // append the converted value to the end of framestr
                            frameStr += "; Converted analogdata is " + convertedValue1;
                        }

                        if (datas.length>1){
                            double convertedValue2 = ConvertRawData(datas[1]);
                            series2.appendData(new DataPoint(Tick, convertedValue2),
                                    false ,
                                    20,
                                    false);

                            // append the converted value to the end of framestr
                            frameStr += "/" + convertedValue2;
                        }
                        frameStr += "/datetime: "+ java.util.Calendar.getInstance().getTime().toString();
                        biopluxResultsTextView.setText(frameStr);

                    }
                } else if (bundle.containsKey(ELAPSED_TIME_EVENT)) {
                    final long elapsedTime = bundle.getLong(ELAPSED_TIME_EVENT);

                    if (elapsedTextView == null) {
                        return;
                    }

                    elapsedTextView.setText(getTimeString(elapsedTime));
                }
            }
        };
```

I am not sure how the API works, but the base class should be `DeviceCommunication.java`? is it hardcoded to 1 second for the thread to sleep then pull data? 

![image](https://user-images.githubusercontent.com/2369864/96560711-edf0ce80-12be-11eb-8f88-0509aee99303.png)

the back to the question, we need to be able to get the updated sensor data every 100ms, please assist.

**Comment by GTelo** [comment]
The **samplingRate** variable is the argument that is passed to the device, this means that in the **original sample code** you will receive **1000 samples per second**. If you want to receive **1 sample every 100ms** you should set the **samplingRate to 10**.

The TIME_1_SECOND constant is only a constant to count the elapsed time upon a start acquisition command, it does not influence the communication workflow with the device.

Notice that in the sample app, in the Device Activity, _onDataAvailable(Parcelable frame)_ callback, we only send the data frame to the handler when the division between the sequence number and the sampling rate is 0, which will be approximately once every second. This is only for demo purposes. To avoid high amounts of data in the sample app, you should **remove this condition** and work with all the data that you receive from the API.
